### ISSUE TITLE
tl_layout conflict

### ISSUE THREAD

**Issue by reluem** [comolo/contao-supertheme#12]
The DCA config of contao-supertheme and [cliffparnitzky/TinyMceFontAwesome](https://github.com/cliffparnitzky/TinyMceFontAwesome) are somehow interfering!

`// Add external_js + external_scss $GLOBALS['TL_DCA']['tl_layout']['palettes']['default'] = str_replace( array(',script;', 'stylesheet,external;', 'stylesheet,external,'), array(',script,external_js;', 'stylesheet,external,external_scss;', 'stylesheet,external,external_scss,'), $GLOBALS['TL_DCA']['tl_layout']['palettes']['default'] );`

interferes with

`$GLOBALS['TL_DCA']['tl_layout']['palettes']['default'] = str_replace('external', 'external,tinyMceFontAwesome', $GLOBALS['TL_DCA']['tl_layout']['palettes']['default']);`

Thus, only the fontawesome-input is visible and the external_js field is hidden/overwritten.

Any proposals for a local dcaconfig change for this issue?

contao 3.5.6
"comolo/contao-supertheme": ">=2.2.5.0,<2.3-dev",
"cliffparnitzky/tiny-mce-font-awesome": ">=2.0.0.0,<2.1-dev",

I also created a ticket here: https://github.com/cliffparnitzky/TinyMceFontAwesome/issues/4

**Comment by comolo** [comment]
The following code change solves the issue. Would be great if the maintainers of "tiny-mce-font-awesome" could apply it. @cliffparnitzky
`
$GLOBALS['TL_DCA']['tl_layout']['palettes']['default'] = str_replace('external', 'external,tinyMceFontAwesome', $GLOBALS['TL_DCA']['tl_layout']['palettes']['default']);
`
to
`$GLOBALS['TL_DCA']['tl_layout']['palettes']['default'] = str_replace(array('external,', 'external;'), array('external,tinyMceFontAwesome,', 'external,tinyMceFontAwesome;' ), $GLOBALS['TL_DCA']['tl_layout']['palettes']['default']);`

Anyway you should update SuperTheme to the latest realese (2.3) for an improved stability.
