### ISSUE TITLE
use mrclay/minify instead of yui

### ISSUE THREAD

**Issue by fritzmg** [comolo/contao-supertheme#13]
Since the development of contao-theme-plus is stagnating I am looking for alternatives. One thing that is possible in contao-theme-plus but isn't in contao-supertheme yet is minifying CSS and JavaScript via PHP, e.g. by using mrclay/minify (`CSSMin` and `JSMin` or `JSMinPlus`) - or another PHP minifying library you prefer.

**Comment by comolo** [comment]
Good suggestion! As soon as I got more free time I will implement this feature.

**Comment by comolo** [comment]
I implemented a minifying library in the contao4 branch of supertheme. Furthermore it's possible to switch on/off minifying in the contao settings :-)
