### ISSUE TITLE
two different CSS collections?

### ISSUE THREAD

**Issue by fritzmg** [comolo/contao-supertheme#14]
I recently noticed, that when supertheme is used and I have regular CSS files (and/or internal CSS files) defined in the page layout, plus additional **S**CSS files, supertheme will generate a second CSS collection for the `<head>` containing only the content of the of the SCSS files. Is this intentional?

**Comment by comolo** [comment]
I remember there was a reason to implement it that way. I think it had to do with caching problems.
I will figure something out.

**Comment by fritzmg** [comment]
Oh I see - maybe the same problem like this one: netzmacht/contao-theme-plus#83 ?

**Comment by comolo** [comment]
I can't tell for sure. But like I sad I will figure out a safe solution.

**Comment by comolo** [comment]
To avoid caching problems as mentioned above I will leave it unchanged.  A second CSS file has not a significant speed impact.
