### ISSUE TITLE
Composer und Versions-Kompatibilität unter Contao 3.5

### ISSUE THREAD

**Issue by michelbalzer** [comolo/contao-supertheme#15]
Ich nutze Contao 3.5.24 und wollte Supertheme installieren. Mir wird die 3.1.1 als installierbar angezeigt, dabei ist diese erst für Contao 4 freigegeben.

Da muss vermutlich noch folgendes in die composer.json:

```
"conflict": {
        "contao/core": "*"
},
```
Noch seltsamer ist nur, dass die 2.2-Versionen über der 2.3 angezeigt werden.

![Screenshot Paketverwaltung](https://cloud.githubusercontent.com/assets/1337412/22925081/bb16ac54-f2a7-11e6-9647-2f4ff115133d.png)

**Comment by comolo** [comment]
Hallo,

die 3.1.1 kann nun nicht mehr mit Contao 3 installiert werden. Das Problem ist nun behoben.
Was die Sortierung angeht habe ich hier ein Ticket aufgemacht: https://github.com/contao-community-alliance/composer-client/issues/307
