### ISSUE TITLE
Contao 4 Managed Edition - Installation

### ISSUE THREAD

**Issue by daniel-nemeth** [comolo/contao-supertheme#16]
Hi,
today I installed your lovely extension on a contao 4 managed edition via composer. Everything worked great during installation.

But after going to the Contao-Install-Tool there are no tables to update and in the backend I can't see your fields at tl_layout.

Does your extension only work with the standard-edition or did I made something wrong?
Thanks

**Comment by henobi** [comment]
Hi and sorry for the late response. I haven't tested SuperTheme with Contao 4.4 yet, but it's definitely on the list to make SuperTheme ready for the latest contao changes.

I will provide an Update soon.
