### ISSUE TITLE
Reihenfolge der JS Dateien wird nicht berücksichtig

### ISSUE THREAD

**Issue by basistom** [comolo/contao-supertheme#19]
Setup:
"comolo/contao-supertheme": "^3.2"
"contao/core-bundle": "4.4.*"

Wird in einem Theme die Reihenfolge für zu integrierende JS-Dateien manipuliert. Wird diese Reihenfolge in der kompilierten JS-Datei nicht umgesetzt. 

Die abgebildete Reihenfolge wird in der folgenden Reihenfolge zusammengefügt:
1. localization/messages_de.js
2. additional_methods.js
3. jquery.validate.js

![screenshot 2018-09-29 12 03 21](https://user-images.githubusercontent.com/4112968/46244488-ba912d80-c3df-11e8-89d1-c994b4c31acc.png)

**Comment by basistom** [comment]
Leider bekomme ich gerade gar keine JavaScript-Datei mehr raus. Ich sehe aber nicht warum.

**Comment by basistom** [comment]
In meiner lokalen Umgebung bekomme ich neben dem folgenden Fehler:
`Warning: array_values() expects parameter 1 to be array, boolean given`
in vendor/comolo/contao-supertheme/src/AssetGenerator/AssetGenerator.php (line 101)

**Comment by henobi** [comment]
Bei mir tritt der Fehler nicht auf. Die Fehlermeldung hat aber weitergeholfen.
Könntest du testen ob es jetzt bei dir klappt.

**Comment by basistom** [comment]
Bis jetzt sieht es sehr gut aus. Ich denke das hat funktioniert.
Danke für die schnellen Anpassungen und die coole Erweiterung!

**Comment by henobi** [comment]
Super! Gerne :)
Falls du noch Feature-Vorschläge hast, nur her damit ;-)
