### ISSUE TITLE
Warning: array_flip(): Can only flip STRING and INTEGER values!

### ISSUE THREAD

**Issue by srhinow** [comolo/contao-supertheme#20]
Ich habe die letzten Commit-Änderungen (#19) per Hand ausgeführt da es keinen passenden Tag dazu gibt.
Jetzt hat er ein weiteres Problem wenn ich die Seite mit app_dev.php/ bearbeite. Dieser Fehler entsteht im AssetGenerator.php Zeile 88. Da $arrTmpOrder = Array ( [0] => ) ist. Daher kann man die Abfrage zur in Zeile 83 so ändern:
        if (empty($arrTmpOrder[0])) {
Dann gibt es keine Fehler mehr.

**Comment by henobi** [comment]
Hi,
könntest du mir noch kurz bestätigen, dass es bei dir läuft? 
Ich habe es soweit mal als 3.3.0 released.

**Comment by srhinow** [comment]
ja bei läuft es  auch nach dem Update auf 3.3.0
