### ISSUE TITLE
Fehler beim Einbinden einer Datei in eine Seite

### ISSUE THREAD

**Issue by basistom** [comolo/contao-supertheme#21]
Ich versuche in einem Contao 4.4.30 eine JavaScript-Datei in einer Seite hinzuzufügen. Beim Speichern der Seite erhalte ich folgende Fehlermeldung:

> Was ist das Problem?
> An exception occurred while executing 'UPDATE tl_page SET tstamp=1544527182, `external_js_order`='a:1:{i:0;s:16:\"17��6袃���&�\";}' WHERE id='6'': SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xDD\xC8\xFD6\x11\xE8...' for column 'external_js_order' at row 1

**Comment by basistom** [comment]
Im Seitenlayout kann ich ohne Probleme Dateien hinzufügen.

**Comment by henobi** [comment]
@basistom Könntest du mal testen ob das Problem mit der letzten Version (dev-master 
a7955fe) behoben ist?

Wichtig: Im Contao Install-Tool muss vorher noch die Datenbank aktualisiert werden.

**Comment by basistom** [comment]
Funktioniert super.

**Comment by henobi** [comment]
Danke für's Feedback :)
Hab's unter 3.3.1 veröffentlicht.

Schönes WE
