### ISSUE TITLE
Doppeltes SCSS-Dateien-Feld im Seitenlayout

### ISSUE THREAD

**Issue by michelbalzer** [comolo/contao-supertheme#9]
Contao 3.2.21, Update von einer 2.10 (zuerst auf 2.11.17, dann direkt auf 3.2.21)

Ich habe im Seitenlayout das SCSS-Dateien-Feld zweimal stehen. Ich kann in beiden Dateien auswählen, gehe ich aber auf Speichern, sind beide Felder leer. Auch wenn ich jeweils nur in einem Auswahlfeld eine Datei auswähle und speicher, sind beide Fehler leer und im FE kommt natürlich auch nichts an.

![bildschirmfoto 2015-08-04 um 12 38 43](https://cloud.githubusercontent.com/assets/1337412/9059008/616a78b2-3aa6-11e5-981a-dd42df01d4da.png)

```
{
    "name": "local/website",
    "description": "A local website project",
    "type": "project",
    "license": "proprietary",
    "require": {
        "comolo/contao-supertheme": ">=2.2.1.0,<2.3-dev",
        "contao-community-alliance/composer-client": "~0.12",
        "contao-legacy/efg": ">=2.2.1.9005,<2.3-dev",
        "contao-legacy/xls_export": ">=3.0.0.9018,<3.1-dev",
        "menatwork/contao-multicolumnwizard": ">=3.3.3.0,<3.4-dev",
        "menatwork/extendedseo": ">=1.3.0.0,<1.4-dev",
        "menatwork/piwiktrackingtag": ">=2.3.3.0,<2.4-dev"
    },
    "prefer-stable": true,
    "minimum-stability": "dev",
    "config": {
        "preferred-install": "dist",
        "cache-dir": "cache",
        "component-dir": "../assets/components"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://legacy-packages-via.contao-community-alliance.org/"
        },
        {
            "type": "artifact",
            "url": "packages"
        },
        {
            "type": "composer",
            "url": "http://legacy-packages-via.contao-community-alliance.org/"
        }
    ],
    "extra": {
        "contao": {
            "migrated": "done"
        }
    }
}
```

**Comment by michelbalzer** [comment]
Okay, deinstallieren und neu installieren hat es dann beim dritten Mal gelöst.

**Comment by comolo** [comment]
Das Problem ist wohl, dass SuperTheme 2.2.2 nicht mit Contao 3.2 kompatibel ist. 
Also einfach die Version **2.2.1** installieren, dann sollte es funktionieren.

Ich werde die composer.json gleich noch entsprechend anpassen.

**Comment by comolo** [comment]
Okay nun installiert der Contao Composer Client automatisch die richtige Version :)
Falls es noch Probleme gibt, bitte nochmal melden...
